server:
  port: 10907
  tomcat:
    max-http-form-post-size: 10485760

spring:
  application:
    name: ural-files
    version: @project.version@
  datasource:
    url: jdbc:postgresql://localhost:10900/ural
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: false
        show_sql: true
        check_nullability: true
        hbm2ddl:
          auto: validate
        default_schema: ural_files
  liquibase:
    enabled: true
    liquibase-schema: public
    database-change-log-table: ural_files_log
    database-change-log-lock-table: ural_files_lock
    change-log: classpath:db/changelog-master.xml
    default-schema: ural_files
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

minio:
  bucket: files
  url: http://localhost:9000
  access-key: ural
  secret-key: uralpass

logging:
  level:
    root: info
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        tomcat:
          util: WARN
